// <auto-generated />
using MeiliLab.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeiliLab.API.Migrations
{
    [DbContext(typeof(MeiliLabDbContext))]
    partial class MeiliLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeiliLab.API.Models.Database.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London",
                            CountryId = 1,
                            County = "Greater London",
                            LineOne = "123 Main Street",
                            PostCode = "SW1A 1AA"
                        },
                        new
                        {
                            Id = 2,
                            City = "Manchester",
                            CountryId = 1,
                            County = "Greater Manchester",
                            LineOne = "456 Oak Avenue",
                            LineTwo = "Apartment 5B",
                            PostCode = "M1 1AA"
                        },
                        new
                        {
                            Id = 3,
                            City = "Birmingham",
                            CountryId = 1,
                            County = "West Midlands",
                            LineOne = "789 High Street",
                            PostCode = "B1 1AA"
                        },
                        new
                        {
                            Id = 4,
                            City = "Edinburgh",
                            CountryId = 2,
                            County = "Midlothian",
                            LineOne = "234 Highland Avenue",
                            LineTwo = "Suite 3C",
                            PostCode = "EH1 1AA"
                        },
                        new
                        {
                            Id = 5,
                            City = "Glasgow",
                            CountryId = 2,
                            County = "Glasgow City",
                            LineOne = "567 Castle Road",
                            PostCode = "G1 1AA"
                        },
                        new
                        {
                            Id = 6,
                            City = "Aberdeen",
                            CountryId = 2,
                            County = "Aberdeenshire",
                            LineOne = "890 Lochside Lane",
                            LineTwo = "Apartment 2A",
                            PostCode = "AB1 1AA"
                        },
                        new
                        {
                            Id = 7,
                            City = "Cardiff",
                            CountryId = 3,
                            County = "Glamorgan",
                            LineOne = "111 Welsh Street",
                            PostCode = "CF1 1AA"
                        },
                        new
                        {
                            Id = 8,
                            City = "Swansea",
                            CountryId = 3,
                            County = "West Glamorgan",
                            LineOne = "222 Dragon Avenue",
                            PostCode = "SA1 1AA"
                        },
                        new
                        {
                            Id = 9,
                            City = "Wrexham",
                            CountryId = 3,
                            County = "Clwyd",
                            LineOne = "333 Valley Road",
                            PostCode = "LL1 1AA"
                        },
                        new
                        {
                            Id = 10,
                            City = "Belfast",
                            CountryId = 4,
                            County = "Antrim",
                            LineOne = "444 Belfast Lane",
                            PostCode = "BT1 1AA"
                        },
                        new
                        {
                            Id = 11,
                            City = "Derry",
                            CountryId = 4,
                            County = "Londonderry",
                            LineOne = "555 Derry Street",
                            PostCode = "BT2 1AA"
                        },
                        new
                        {
                            Id = 12,
                            City = "Armagh",
                            CountryId = 4,
                            County = "Armagh",
                            LineOne = "666 Armagh Road",
                            PostCode = "BT3 1AA"
                        },
                        new
                        {
                            Id = 13,
                            City = "Dublin",
                            CountryId = 5,
                            County = "Dublin",
                            LineOne = "777 Dublin Street",
                            PostCode = "D01 1AA"
                        },
                        new
                        {
                            Id = 14,
                            City = "Cork",
                            CountryId = 5,
                            County = "Cork",
                            LineOne = "888 Cork Avenue",
                            PostCode = "T12 1AA"
                        },
                        new
                        {
                            Id = 15,
                            City = "Galway",
                            CountryId = 5,
                            County = "Galway",
                            LineOne = "999 Galway Road",
                            PostCode = "H91 1AA"
                        },
                        new
                        {
                            Id = 16,
                            City = "Paris",
                            CountryId = 6,
                            County = "Ile-de-France",
                            LineOne = "101 Paris Street",
                            PostCode = "75001"
                        },
                        new
                        {
                            Id = 17,
                            City = "Marseille",
                            CountryId = 6,
                            County = "Provence-Alpes-Côte d'Azur",
                            LineOne = "202 Marseille Avenue",
                            PostCode = "13001"
                        },
                        new
                        {
                            Id = 18,
                            City = "Lyon",
                            CountryId = 6,
                            County = "Auvergne-Rhône-Alpes",
                            LineOne = "303 Lyon Road",
                            PostCode = "69001"
                        },
                        new
                        {
                            Id = 19,
                            City = "Madrid",
                            CountryId = 7,
                            County = "Community of Madrid",
                            LineOne = "404 Madrid Street",
                            PostCode = "28001"
                        },
                        new
                        {
                            Id = 20,
                            City = "Barcelona",
                            CountryId = 7,
                            County = "Catalonia",
                            LineOne = "505 Barcelona Avenue",
                            PostCode = "08001"
                        },
                        new
                        {
                            Id = 21,
                            City = "Valencia",
                            CountryId = 7,
                            County = "Valencian Community",
                            LineOne = "606 Valencia Road",
                            PostCode = "46001"
                        },
                        new
                        {
                            Id = 22,
                            City = "Lisbon",
                            CountryId = 8,
                            County = "Lisbon District",
                            LineOne = "707 Lisbon Street",
                            PostCode = "1000-001"
                        },
                        new
                        {
                            Id = 23,
                            City = "Porto",
                            CountryId = 8,
                            County = "Porto District",
                            LineOne = "808 Porto Avenue",
                            PostCode = "4000-001"
                        },
                        new
                        {
                            Id = 24,
                            City = "Faro",
                            CountryId = 8,
                            County = "Faro District",
                            LineOne = "909 Faro Road",
                            PostCode = "8000-001"
                        },
                        new
                        {
                            Id = 25,
                            City = "Rome",
                            CountryId = 9,
                            County = "Lazio",
                            LineOne = "101 Rome Street",
                            PostCode = "00100"
                        },
                        new
                        {
                            Id = 26,
                            City = "Milan",
                            CountryId = 9,
                            County = "Lombardy",
                            LineOne = "202 Milan Avenue",
                            PostCode = "20100"
                        },
                        new
                        {
                            Id = 27,
                            City = "Florence",
                            CountryId = 9,
                            County = "Tuscany",
                            LineOne = "303 Florence Road",
                            PostCode = "50100"
                        },
                        new
                        {
                            Id = 28,
                            City = "Berlin",
                            CountryId = 10,
                            County = "Berlin",
                            LineOne = "404 Berlin Street",
                            PostCode = "10115"
                        },
                        new
                        {
                            Id = 29,
                            City = "Hamburg",
                            CountryId = 10,
                            County = "Hamburg",
                            LineOne = "505 Hamburg Avenue",
                            PostCode = "20095"
                        },
                        new
                        {
                            Id = 30,
                            City = "Munich",
                            CountryId = 10,
                            County = "Bavaria",
                            LineOne = "606 Munich Road",
                            PostCode = "80331"
                        });
                });

            modelBuilder.Entity("MeiliLab.API.Models.Database.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ENG",
                            Name = "England"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SCT",
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = 3,
                            Code = "WAL",
                            Name = "Wales"
                        },
                        new
                        {
                            Id = 4,
                            Code = "NIR",
                            Name = "Northern Ireland"
                        },
                        new
                        {
                            Id = 5,
                            Code = "IRE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 6,
                            Code = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 8,
                            Code = "POR",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 10,
                            Code = "GER",
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("MeiliLab.API.Models.Database.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Beds")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Bathrooms = 1,
                            Beds = 1,
                            CountryId = 1,
                            Description = "A comfortable apartment in the heart of London.",
                            Guests = 2,
                            Location = "123 Main Street, London",
                            Name = "Cozy Apartment in London",
                            PricePerNight = 100.00m,
                            PropertyType = 1,
                            Rating = 4.5,
                            Rooms = 2
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 4,
                            Bathrooms = 2,
                            Beds = 2,
                            CountryId = 2,
                            Description = "A charming cottage with beautiful views of Edinburgh.",
                            Guests = 4,
                            Location = "234 Highland Avenue, Edinburgh",
                            Name = "Scenic Cottage in Edinburgh",
                            PricePerNight = 150.00m,
                            PropertyType = 5,
                            Rating = 4.7999999999999998,
                            Rooms = 3
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 7,
                            Bathrooms = 1,
                            Beds = 1,
                            CountryId = 3,
                            Description = "A peaceful retreat in the heart of Cardiff, Wales.",
                            Guests = 2,
                            Location = "111 Welsh Street, Cardiff",
                            Name = "Welsh Retreat in Cardiff",
                            PricePerNight = 80.00m,
                            PropertyType = 1,
                            Rating = 4.2000000000000002,
                            Rooms = 1
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 10,
                            Bathrooms = 3,
                            Beds = 3,
                            CountryId = 4,
                            Description = "A luxurious penthouse with stunning views of Belfast.",
                            Guests = 6,
                            Location = "444 Belfast Lane, Belfast",
                            Name = "Spacious Penthouse in Belfast",
                            PricePerNight = 250.00m,
                            PropertyType = 10,
                            Rating = 4.9000000000000004,
                            Rooms = 4
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 13,
                            Bathrooms = 1,
                            Beds = 1,
                            CountryId = 5,
                            Description = "Modern apartment in the heart of Dublin city center.",
                            Guests = 2,
                            Location = "777 Dublin Street, Dublin",
                            Name = "Dublin City Center Apartment",
                            PricePerNight = 120.00m,
                            PropertyType = 9,
                            Rating = 4.7000000000000002,
                            Rooms = 1
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 16,
                            Bathrooms = 1,
                            Beds = 1,
                            CountryId = 6,
                            Description = "Chic studio in the heart of Paris, close to the Eiffel Tower.",
                            Guests = 3,
                            Location = "101 Paris Street, Paris",
                            Name = "Elegant Parisian Studio",
                            PricePerNight = 180.00m,
                            PropertyType = 0,
                            Rating = 4.5999999999999996,
                            Rooms = 2
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 20,
                            Bathrooms = 4,
                            Beds = 4,
                            CountryId = 7,
                            Description = "A beautiful villa with a private pool near Barcelona's beaches.",
                            Guests = 8,
                            Location = "505 Barcelona Avenue, Barcelona",
                            Name = "Seaside Villa in Barcelona",
                            PricePerNight = 300.00m,
                            PropertyType = 0,
                            Rating = 4.7999999999999998,
                            Rooms = 5
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 22,
                            Bathrooms = 2,
                            Beds = 2,
                            CountryId = 8,
                            Description = "Charming townhouse with traditional Portuguese architecture.",
                            Guests = 5,
                            Location = "707 Lisbon Street, Lisbon",
                            Name = "Historic Lisbon Townhouse",
                            PricePerNight = 160.00m,
                            PropertyType = 4,
                            Rating = 4.5,
                            Rooms = 3
                        },
                        new
                        {
                            Id = 9,
                            AddressId = 25,
                            Bathrooms = 1,
                            Beds = 1,
                            CountryId = 9,
                            Description = "Cozy apartment with a view of the Colosseum.",
                            Guests = 3,
                            Location = "101 Rome Street, Rome",
                            Name = "Roman Holiday Apartment",
                            PricePerNight = 140.00m,
                            PropertyType = 1,
                            Rating = 4.4000000000000004,
                            Rooms = 2
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 30,
                            Bathrooms = 2,
                            Beds = 2,
                            CountryId = 10,
                            Description = "Tranquil retreat in the Bavarian countryside.",
                            Guests = 4,
                            Location = "606 Munich Road, Munich",
                            Name = "Munich Countryside Retreat",
                            PricePerNight = 200.00m,
                            PropertyType = 13,
                            Rating = 4.5999999999999996,
                            Rooms = 3
                        },
                        new
                        {
                            Id = 11,
                            AddressId = 9,
                            Bathrooms = 1,
                            Beds = 1,
                            CountryId = 3,
                            Description = "Escape to nature with this lakeside cabin in Wales.",
                            Guests = 2,
                            Location = "333 Valley Road, Wrexham",
                            Name = "Serene Lakeside Cabin in Wales",
                            PricePerNight = 90.00m,
                            PropertyType = 9,
                            Rating = 4.2999999999999998,
                            Rooms = 1
                        },
                        new
                        {
                            Id = 12,
                            AddressId = 24,
                            Bathrooms = 3,
                            Beds = 3,
                            CountryId = 8,
                            Description = "Exclusive villa with direct access to the Algarve beaches.",
                            Guests = 6,
                            Location = "909 Faro Road, Faro",
                            Name = "Luxury Beachfront Villa in Algarve",
                            PricePerNight = 280.00m,
                            PropertyType = 3,
                            Rating = 4.9000000000000004,
                            Rooms = 4
                        },
                        new
                        {
                            Id = 13,
                            AddressId = 28,
                            Bathrooms = 1,
                            Beds = 1,
                            CountryId = 10,
                            Description = "Modern loft in the heart of Berlin's vibrant city center.",
                            Guests = 3,
                            Location = "404 Berlin Street, Berlin",
                            Name = "Berlin City Loft",
                            PricePerNight = 170.00m,
                            PropertyType = 1,
                            Rating = 4.7000000000000002,
                            Rooms = 2
                        });
                });

            modelBuilder.Entity("MeiliLab.API.Models.Database.Property", b =>
                {
                    b.HasOne("MeiliLab.API.Models.Database.Country", null)
                        .WithMany("Properties")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeiliLab.API.Models.Database.Country", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
